name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -o yms -v ./...

    - name: Test
      run: go test -o yms -v ./...
    
    - name: Release
      uses: actions/release@v2
      with:
        release-branch: main
        release-name: yms
        release-notes: |
          - ci/cd release
        tag-name: 'v${{ env.GITHUB_RUN_NUMBER }}'
        tag-message: '${{ env.GITHUB_RUN_NUMBER }}'
        assets: yms
       